### 실습과제 1

In [ ]:
import numpy as np

In [ ]:
A = np.random.randint(1, 99, size=(2,8))

In [ ]:
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
print(A.shape)
print(A.shape[0])
print(A.shape[1])
print(A)

(2, 8)
2
8
[[ 1  1 63 64 11 81 57 24]
 [68 70 42 89 68 41 98 33]]


In [ ]:
max_value = None
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        if max_value is None or A[i, j] > max_value:
            max_value = A[i, j]
print("All Max : ", max_value)


for i in range(A.shape[0]):
    max_value2 = None
    for j in range(A.shape[1]):
        if max_value2 is None or A[i, j] > max_value2:
            max_value2 = A[i, j]
    print("SubMax", i, ":", max_value2)

All Max :  98
SubMax 0 : 81
SubMax 1 : 98


In [ ]:
B = A.reshape(2,2,4)

In [ ]:
print(B.shape)
print(B)

(2, 2, 4)
[[[ 1  1 63 64]
  [11 81 57 24]]

 [[68 70 42 89]
  [68 41 98 33]]]


### 실습과제 2

In [ ]:
C = B.copy()

In [ ]:
C[:,:,0:2] = B[:,:,2:]
C[:,:,2:] = B[:,:,:2]

In [ ]:
print(C)

[[[63 64  1  1]
  [57 24 11 81]]

 [[42 89 68 70]
  [98 33 68 41]]]
